name: Elixir CI

on: push

jobs:
  test:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.11

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Check Format
      run: mix format --check-formatted
    - name: Run Tests
      run: mix test
